version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
    volumes:
      - ./data:/data
      - ./plugins:/plugins
      - ./import:/import

  spacy-service:
    build: .
    ports:
      - "5000:5000"  # Or whatever port your spaCy service uses